
## The directory provides some cross-app pages, like the main listing ("/")
civi_cxn_dir:
    resource: "@CiviCxnDirBundle/Resources/config/routing.yml"
    prefix:   /

## For every application, define standard routes for registration and metadata.
civi_cxn_app:
    resource: "@CiviCxnAppBundle/Resources/config/routing.yml"
    prefix:   /{appId}

## For the cron application, define some custom screens.
civi_cxn_cron:
    resource: "@CiviCxnCronBundle/Resources/config/routing.yml"
    prefix:   /app:org.civicrm.cron
    defaults:
      appId:  app:org.civicrm.cron

## For the profile application, define some custom screens.
civi_cxn_profile:
    resource: "@CiviCxnProfileBundle/Resources/config/routing.yml"
    prefix:   /

civi_cxn_crl:
    resource: "@CiviCxnCrlBundle/Resources/config/routing.yml"
    prefix:   /ca

## A service for checking the accessibility of addresses
civi_cxn_address_checker:
    resource: "@CiviCxnAddressCheckerBundle/Resources/config/routing.yml"
    prefix:   /
