org_civicrm_profile_settings:
    path:     /app:org.civicrm.profile/{cxnId}/settings
    defaults: { _controller: civi_cxn_profile.admin_controller:settingsAction }

org_civicrm_profile_view:
    path:   /profile/{pubId}
    defaults: { _controller: civi_cxn_profile.public_controller:viewAction }