civi_cxn_dirsvc_homepage:
    path:     /
    defaults: { _controller: civi_cxn_dirsvc.dirsvc_controller:indexAction }

civi_cxn_dirsvc_all_apps:
    path:     /cxn/apps
    defaults: { _controller: civi_cxn_dirsvc.dirsvc_controller:appsAction }
