civi_cxn_app_apps:
    path:     /{appId}/cxn/apps
    defaults: { _controller: civi_cxn_app.cxn_app_controller:appsAction }

civi_cxn_app_metadata:
    path:     /{appId}/cxn/metadata.json
    defaults: { _controller: civi_cxn_app.cxn_app_controller:metadataAction }

civi_cxn_app_register:
    path:     /{appId}/cxn/register
    defaults: { _controller: civi_cxn_app.cxn_app_controller:registerAction }
