civi_cxn_app_apps:
    path:     /cxn/apps
    defaults: { _controller: civi_cxn_app.cxn_app_controller:appsAction }

civi_cxn_app_metadata:
    path:     /cxn/metadata.json
    defaults: { _controller: civi_cxn_app.cxn_app_controller:metadataAction }

civi_cxn_app_register:
    path:     /cxn/register
    defaults: { _controller: civi_cxn_app.cxn_app_controller:registerAction }
