parameters:
  civi_cxn_app.data_dir: '%kernel.root_dir%/cxn'

services:

  civi_cxn_app.app_store:
    class: Civi\Cxn\AppBundle\FileAppStore
    arguments: ['%civi_cxn_app.data_dir%', '@router']

  civi_cxn_app.cxn_store:
    class: Civi\Cxn\AppBundle\DoctrineCxnStore
    arguments: ['@doctrine.orm.entity_manager']

  civi_cxn_app.command.app_cleanup_command:
    class: Civi\Cxn\AppBundle\Command\AppCleanupCommand
    arguments: ["@civi_cxn_app.links"]
    tags:
      - { name: console.command }

  civi_cxn_app.command.app_get_command:
    class: Civi\Cxn\AppBundle\Command\AppGetCommand
    arguments: ["@civi_cxn_app.app_store"]
    tags:
      - { name: console.command }

  civi_cxn_app.command.app_init_command:
    class: Civi\Cxn\AppBundle\Command\AppInitCommand
    arguments: ["@civi_cxn_app.app_store"]
    tags:
      - { name: console.command }

  civi_cxn_app.command.cxn_get_command:
    class: Civi\Cxn\AppBundle\Command\CxnGetCommand
    arguments: ["@civi_cxn_app.cxn_store"]
    tags:
      - { name: console.command }

  civi_cxn_app.command.cxn_call_command:
    class: Civi\Cxn\AppBundle\Command\CxnCallCommand
    arguments: ["@civi_cxn_app.app_store", "@civi_cxn_app.cxn_store", "@logger"]
    tags:
      - { name: console.command }

  civi_cxn_app.command.cxn_link_command:
    class: Civi\Cxn\AppBundle\Command\CxnLinkCommand
    arguments: ["@civi_cxn_app.links", "@civi_cxn_app.cxn_store", "@logger"]
    tags:
      - { name: console.command }

  civi_cxn_app.cxn_app_controller:
    class: Civi\Cxn\AppBundle\Controller\CxnAppController
    arguments:
      - "@service_container"
      - "@civi_cxn_app.app_store"
      - "@civi_cxn_app.cxn_store"
      - "@logger"
      - "@civi_cxn_app.links"
    tags:
      - { name: monolog.logger, channel: 'register' }

  civi_cxn_app.links:
    class: Civi\Cxn\AppBundle\CxnLinks
    arguments:
      - "@router"
      - "@logger"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: monolog.logger, channel: 'settings' }

  kernel.listener.your_listener_name:
    class: Civi\Cxn\AppBundle\EventListener\CxnTokenListener
    arguments:
      - "@civi_cxn_app.cxn_store"
      - "@doctrine.orm.entity_manager"

    tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
